//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Alterego
{
    [Serializable]
    public class EgoArmsMsg : Message
    {
        public const string k_RosMessageName = "alterego_msgs/EgoArms";
        public override string RosMessageName => k_RosMessageName;

        public double[] q_des;
        public double[] qd_des;
        public double[] qdd_des;

        public EgoArmsMsg()
        {
            this.q_des = new double[0];
            this.qd_des = new double[0];
            this.qdd_des = new double[0];
        }

        public EgoArmsMsg(double[] q_des, double[] qd_des, double[] qdd_des)
        {
            this.q_des = q_des;
            this.qd_des = qd_des;
            this.qdd_des = qdd_des;
        }

        public static EgoArmsMsg Deserialize(MessageDeserializer deserializer) => new EgoArmsMsg(deserializer);

        private EgoArmsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.q_des, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.qd_des, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.qdd_des, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.q_des);
            serializer.Write(this.q_des);
            serializer.WriteLength(this.qd_des);
            serializer.Write(this.qd_des);
            serializer.WriteLength(this.qdd_des);
            serializer.Write(this.qdd_des);
        }

        public override string ToString()
        {
            return "EgoArmsMsg: " +
            "\nq_des: " + System.String.Join(", ", q_des.ToList()) +
            "\nqd_des: " + System.String.Join(", ", qd_des.ToList()) +
            "\nqdd_des: " + System.String.Join(", ", qdd_des.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
