//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Alterego
{
    [Serializable]
    public class LowerBodyStateMsg : Message
    {
        public const string k_RosMessageName = "alterego_msgs/LowerBodyState";
        public override string RosMessageName => k_RosMessageName;

        public double right_wheel_enc;
        public double left_wheel_enc;
        public double right_wheel_pos;
        public double left_wheel_pos;
        public double wheels_angular_pos;
        public double right_wheel_vel;
        public double left_wheel_vel;
        public double wheels_angular_vel;
        public double mobile_base_pos_x;
        public double mobile_base_pos_y;
        public double mobile_base_lin_displacement;
        public double mobile_base_lin_vel;
        public double yaw_angle;
        public double yaw_rate;
        public double mobile_base_ang_vel;
        public double pitch_angle;
        public double pitch_rate;
        public double base_battery_voltage;

        public LowerBodyStateMsg()
        {
            this.right_wheel_enc = 0.0;
            this.left_wheel_enc = 0.0;
            this.right_wheel_pos = 0.0;
            this.left_wheel_pos = 0.0;
            this.wheels_angular_pos = 0.0;
            this.right_wheel_vel = 0.0;
            this.left_wheel_vel = 0.0;
            this.wheels_angular_vel = 0.0;
            this.mobile_base_pos_x = 0.0;
            this.mobile_base_pos_y = 0.0;
            this.mobile_base_lin_displacement = 0.0;
            this.mobile_base_lin_vel = 0.0;
            this.yaw_angle = 0.0;
            this.yaw_rate = 0.0;
            this.mobile_base_ang_vel = 0.0;
            this.pitch_angle = 0.0;
            this.pitch_rate = 0.0;
            this.base_battery_voltage = 0.0;
        }

        public LowerBodyStateMsg(double right_wheel_enc, double left_wheel_enc, double right_wheel_pos, double left_wheel_pos, double wheels_angular_pos, double right_wheel_vel, double left_wheel_vel, double wheels_angular_vel, double mobile_base_pos_x, double mobile_base_pos_y, double mobile_base_lin_displacement, double mobile_base_lin_vel, double yaw_angle, double yaw_rate, double mobile_base_ang_vel, double pitch_angle, double pitch_rate, double base_battery_voltage)
        {
            this.right_wheel_enc = right_wheel_enc;
            this.left_wheel_enc = left_wheel_enc;
            this.right_wheel_pos = right_wheel_pos;
            this.left_wheel_pos = left_wheel_pos;
            this.wheels_angular_pos = wheels_angular_pos;
            this.right_wheel_vel = right_wheel_vel;
            this.left_wheel_vel = left_wheel_vel;
            this.wheels_angular_vel = wheels_angular_vel;
            this.mobile_base_pos_x = mobile_base_pos_x;
            this.mobile_base_pos_y = mobile_base_pos_y;
            this.mobile_base_lin_displacement = mobile_base_lin_displacement;
            this.mobile_base_lin_vel = mobile_base_lin_vel;
            this.yaw_angle = yaw_angle;
            this.yaw_rate = yaw_rate;
            this.mobile_base_ang_vel = mobile_base_ang_vel;
            this.pitch_angle = pitch_angle;
            this.pitch_rate = pitch_rate;
            this.base_battery_voltage = base_battery_voltage;
        }

        public static LowerBodyStateMsg Deserialize(MessageDeserializer deserializer) => new LowerBodyStateMsg(deserializer);

        private LowerBodyStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.right_wheel_enc);
            deserializer.Read(out this.left_wheel_enc);
            deserializer.Read(out this.right_wheel_pos);
            deserializer.Read(out this.left_wheel_pos);
            deserializer.Read(out this.wheels_angular_pos);
            deserializer.Read(out this.right_wheel_vel);
            deserializer.Read(out this.left_wheel_vel);
            deserializer.Read(out this.wheels_angular_vel);
            deserializer.Read(out this.mobile_base_pos_x);
            deserializer.Read(out this.mobile_base_pos_y);
            deserializer.Read(out this.mobile_base_lin_displacement);
            deserializer.Read(out this.mobile_base_lin_vel);
            deserializer.Read(out this.yaw_angle);
            deserializer.Read(out this.yaw_rate);
            deserializer.Read(out this.mobile_base_ang_vel);
            deserializer.Read(out this.pitch_angle);
            deserializer.Read(out this.pitch_rate);
            deserializer.Read(out this.base_battery_voltage);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.right_wheel_enc);
            serializer.Write(this.left_wheel_enc);
            serializer.Write(this.right_wheel_pos);
            serializer.Write(this.left_wheel_pos);
            serializer.Write(this.wheels_angular_pos);
            serializer.Write(this.right_wheel_vel);
            serializer.Write(this.left_wheel_vel);
            serializer.Write(this.wheels_angular_vel);
            serializer.Write(this.mobile_base_pos_x);
            serializer.Write(this.mobile_base_pos_y);
            serializer.Write(this.mobile_base_lin_displacement);
            serializer.Write(this.mobile_base_lin_vel);
            serializer.Write(this.yaw_angle);
            serializer.Write(this.yaw_rate);
            serializer.Write(this.mobile_base_ang_vel);
            serializer.Write(this.pitch_angle);
            serializer.Write(this.pitch_rate);
            serializer.Write(this.base_battery_voltage);
        }

        public override string ToString()
        {
            return "LowerBodyStateMsg: " +
            "\nright_wheel_enc: " + right_wheel_enc.ToString() +
            "\nleft_wheel_enc: " + left_wheel_enc.ToString() +
            "\nright_wheel_pos: " + right_wheel_pos.ToString() +
            "\nleft_wheel_pos: " + left_wheel_pos.ToString() +
            "\nwheels_angular_pos: " + wheels_angular_pos.ToString() +
            "\nright_wheel_vel: " + right_wheel_vel.ToString() +
            "\nleft_wheel_vel: " + left_wheel_vel.ToString() +
            "\nwheels_angular_vel: " + wheels_angular_vel.ToString() +
            "\nmobile_base_pos_x: " + mobile_base_pos_x.ToString() +
            "\nmobile_base_pos_y: " + mobile_base_pos_y.ToString() +
            "\nmobile_base_lin_displacement: " + mobile_base_lin_displacement.ToString() +
            "\nmobile_base_lin_vel: " + mobile_base_lin_vel.ToString() +
            "\nyaw_angle: " + yaw_angle.ToString() +
            "\nyaw_rate: " + yaw_rate.ToString() +
            "\nmobile_base_ang_vel: " + mobile_base_ang_vel.ToString() +
            "\npitch_angle: " + pitch_angle.ToString() +
            "\npitch_rate: " + pitch_rate.ToString() +
            "\nbase_battery_voltage: " + base_battery_voltage.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
