//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Alterego
{
    [Serializable]
    public class CloseGStreamerRequest : Message
    {
        public const string k_RosMessageName = "alterego_msgs/CloseGStreamer";
        public override string RosMessageName => k_RosMessageName;


        public CloseGStreamerRequest()
        {
        }
        public static CloseGStreamerRequest Deserialize(MessageDeserializer deserializer) => new CloseGStreamerRequest(deserializer);

        private CloseGStreamerRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "CloseGStreamerRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
