//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Alterego
{
    [Serializable]
    public class EnableAutoModeServiceRequest : Message
    {
        public const string k_RosMessageName = "alterego_msgs/EnableAutoModeService";
        public override string RosMessageName => k_RosMessageName;

        public bool enable;

        public EnableAutoModeServiceRequest()
        {
            this.enable = false;
        }

        public EnableAutoModeServiceRequest(bool enable)
        {
            this.enable = enable;
        }

        public static EnableAutoModeServiceRequest Deserialize(MessageDeserializer deserializer) => new EnableAutoModeServiceRequest(deserializer);

        private EnableAutoModeServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable);
        }

        public override string ToString()
        {
            return "EnableAutoModeServiceRequest: " +
            "\nenable: " + enable.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
