//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Alterego
{
    [Serializable]
    public class LaunchGStreamerRequest : Message
    {
        public const string k_RosMessageName = "alterego_msgs/LaunchGStreamer";
        public override string RosMessageName => k_RosMessageName;

        public string ip_address;

        public LaunchGStreamerRequest()
        {
            this.ip_address = "";
        }

        public LaunchGStreamerRequest(string ip_address)
        {
            this.ip_address = ip_address;
        }

        public static LaunchGStreamerRequest Deserialize(MessageDeserializer deserializer) => new LaunchGStreamerRequest(deserializer);

        private LaunchGStreamerRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ip_address);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ip_address);
        }

        public override string ToString()
        {
            return "LaunchGStreamerRequest: " +
            "\nip_address: " + ip_address.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
