//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Alterego
{
    [Serializable]
    public class LaunchGStreamerResponse : Message
    {
        public const string k_RosMessageName = "alterego_msgs/LaunchGStreamer";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public LaunchGStreamerResponse()
        {
            this.success = false;
        }

        public LaunchGStreamerResponse(bool success)
        {
            this.success = success;
        }

        public static LaunchGStreamerResponse Deserialize(MessageDeserializer deserializer) => new LaunchGStreamerResponse(deserializer);

        private LaunchGStreamerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "LaunchGStreamerResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
